language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
notifications:
email:
  - jasnapaka@jasnapaka.com
script:
    - phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)